### ISSUE TITLE
Mongoose .update and .findByIdAndUpdate seems to not trigger 'patching'  

### ISSUE THREAD

**Issue by Mathiasduc** [codepunkt/mongoose-patch-history#11]
Hello,

As the title say, i can only get the plugin to work when i, like the doc,  do a ` Model.find()` ,  then, on the found document, do a `.set().save()` .
I'm a begginner so i might be wrong, but is this a Mongoose limitations? I found this bit in the Mongoose doc: 

> Although values are casted to their appropriate types when using update, the following are not applied:
> 
> defaults
> setters
> validators
> middleware
> If you need those features, use the traditional approach of first retrieving the document.

Is this the reason?

**Comment by codepunkt** [comment]
It might be. I haven't used this for quite a while so i'm not too sure about the mongoose internals anymore. If it is possible, it would be great if this library would support it.

Maybe someone else can chime in and clarify?

**Comment by Mathiasduc** [comment]
After inquiring further, it seems do be impossible. 
`.update` and `.findOneAndUpdate` (same as `.findByIdAndUpdate`) do not return the original documents, making it impossible to make a snapshot of it to then compare it with `JSONpatch.compare`.
Tried a lot of workaround, none worked.

**Comment by codepunkt** [comment]
I remember trying out a few different ways to satisfy all or at least the most common used mongoose APIs when writing this, but coming up empty-handed on a lot of them.

Thanks a lot for trying! It's a pity 😞

**Comment by compwright** [comment]
This is possible, see https://github.com/mimani/mongoose-diff-history/blob/master/diffHistory.js#L164
