### ISSUE TITLE
All of a sudden started to get an error saying TypeError: Cannot set property '_original' of null

### ISSUE THREAD

**Issue by THPubs** [codepunkt/mongoose-patch-history#22]
Everything seems to work well. But all of a sudden I got the following error:

    TypeError: Cannot set property '_original' of null
        at /Users/pubudu/Projects/FleetManager/fm-main-api/node_modules/mongoose-patch-history/lib/index.js:191:21

Unfortunately, I was unable to find the exact issue.

This is how I attached it to my model:

    EquipmentSchema.plugin(patchHistory, {
      mongoose,
      name: 'equipmentHistory'
    });

I also tried setting `trackOriginalValue: false` but still it did not work. Any idea what's happening?

**Comment by florojunior** [comment]
This error occurs when I try to perform an update with a nonexistent ObjectId in the collection.

**Comment by codepunkt** [comment]
@THPubs @florojunior Thanks for reporting this problem and thanks for adding additional context as to how/when this occurs.

- Which versions of `mongodb`, `mongoose` and `mongoose-patch-history` do you use?
- Can you provide a minimum, reproducible example?

**Comment by mapo-job** [comment]
I suggest to just ignore the history if the document was not updated, at line 173 add: if(!doc) next();

```
  schema.post('findOneAndUpdate', function (doc, next) {
    if(!doc) next();  //<-- here
    if (!this.options.new) {
      return postUpdateOne.call(this, {}, next);
    }
```

**Comment by MartinLoeper** [comment]
I ran into the same bug today!
I observed the following: We call findOneAndUpdate in our code and the query does not match anything.
The following line then causes a null pointer: https://github.com/codepunkt/mongoose-patch-history/blob/master/lib/index.js#L177

This is because `doc` is null in this case.

**Comment by mapo-job** [comment]
Here is an example to reproduce the issue:
```javascript
    const mongoose = require('mongoose');
    const Schema = mongoose.Schema;
    const patchHistory = require('mongoose-patch-history').default;
 
    const PostSchema = new Schema({
        _id: { type: String },
        title: { type: String, required: true },
        comments: Array
    }, {_id:false});
 
    PostSchema.plugin(patchHistory, { mongoose, name: 'postPatches' });
 
    const Post = mongoose.model('Post', PostSchema);
    let post= await Post.create({_id: "post", title:"first", comments:["ok"]});
    console.log('Ok', post);
 
    post= await Post.findOneAndUpdate({_id:"inexistence"}, {title:"new", comments:["fine"]});
    console.log(post);
/*
    Ok { comments: [ 'ok' ], _id: 'post', title: 'first', __v: 0 }
    2018-06-01T14:03:26.169Z - error: Unhandled Rejection at: Promise [object Promise] - reason ==> TypeError: Cannot set property '_original' of null
    at C:\examples\node_modules\mongoose-patch-history\lib\index.js:193:21
    at tryCatcher (C:\examples\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\examples\node_modules\bluebird\js\release\promise.js:512:31)
...
*/
```

**Comment by tryrestarting** [comment]
Updating mongoose to v5.1.7 seems to do the trick for me.

**Comment by codepunkt** [comment]
Anyone up for providing a PR for this? I don't have the time at the moment.
