### ISSUE TITLE
Some troubles with virtual path

### ISSUE THREAD

**Issue by danks1234** [codepunkt/mongoose-patch-history#23]
Servus,
while trying to get the plugin to work I had a few issues, most of them were lack of understanding on my end, so it isn't that much of a biggie, but I thought I'd post it here in case someone else runs into the issue.

At first I had this:
```
(function (exports, require, module, __filename, __dirname) { import patchHistory from 'mongoose-patch-history';
SyntaxError: Unexpected identifier
```

Probably my settings, had to use require instead and when calling the plugin I had to make sure I used 
`computerSchema.plugin(patchHistory.default, { mongoose, name: 'computerHist' });`

Then I had this:
```
\node_modules\mongoose\lib\schema.js:1601
    throw new Error('Virtual path "' + name + '"' +
Error: Virtual path "patches" conflicts with a real path in the schema
```

I'm unsure as to that path "patches" being used, I don't really have an overview of all the things that are going on in the project, so I changed this line a bit:
```
var Patches = createPatchModel(options);
  schema.statics.Patches = Patches;
  schema.virtual('patches_hist').get(function () {
    return Patches;
  });
```

Working like a charm afterwards, maybe the name "patches" is a bit too generic, thanks for the awesome work!

**Comment by codepunkt** [comment]
Thanks for posting this here, it might help others!
