### ISSUE TITLE
Update Deps 

### ISSUE THREAD

**Issue by codepunkt** [codepunkt/mongoose-patch-history#4]

**Comment by mrchess** [comment]
This looks cool. I might use it. What deps were u thinking of updating?

**Comment by codepunkt** [comment]
Was just thinking about updating all deps to their newest versions. Haven't looked into it for the last few weeks because for my usecase this just works and i've been busy with [css-spring](https://github.com/codepunkt/css-spring). If you try it out, let me know if you encounter any problems :)

**Comment by mrchess** [comment]
Yeah I most definitely will. I was about to try to write something similar, and was super happy when I stumbled upon this! Really appreciate you publishing this mate 👍

**Comment by codepunkt** [comment]
Feedback is always welcome. Constructive criticism, new ideas, a simpler API etc! For what it is (a first attempt to do something like this) it is performing quite well on my end :)

Updated the deps, added testing for node 7.x and added `yarn.lock`.

**Comment by mrchess** [comment]
Quick question for you. How big were your patches tables getting? Just wondering if you ran into performance issues at some point, though it doesn't seem like you should.

**Comment by codepunkt** [comment]
No issues as of now - i don't have a really large database with lots of editing though, so i'd be happy to hear about your experience! :)
