### ISSUE TITLE
TypeError: fn is not a function

### ISSUE THREAD

**Issue by mrchess** [codepunkt/mongoose-patch-history#5]
In my code I had:

`schema.plugin(patchHistory, {mongoose,...`

Which threw the error: 
```
TypeError: fn is not a function
    at Schema.plugin (/Users/himrc/Sites/dama/node_modules/mongoose/lib/schema.js:1133:3)
```

I was able to fix it by adding `default`. Not sure why I needed to do this.

The working code for me was:

`schema.plugin(patchHistory.default, {mongoose,...`

**Comment by codepunkt** [comment]
I guess you required the module like this?

```javascript
var patchHistory = require('mongoose-patch-history');
```

**Comment by mrchess** [comment]
`const patchHistory = require('mongoose-patch-history');`

Ah I see, you're using `import`... gotcha.

**Comment by mrchess** [comment]
I changed my `express` to use `babel-node`. 💥

**Comment by codepunkt** [comment]
@mrchess We might consider changing this. I'm not sure if there's a way with babel to have both require and import work without having to resort to `default` when requiring.
