### ISSUE TITLE
Cannot perform an `add` operation at the desired path

### ISSUE THREAD

**Issue by intermx-reddysai** [codepunkt/mongoose-patch-history#68]
NodeJS: 12.16.3
npm: 6.14.4
OS: ubuntu

I'm trying to read the initial patch record with help of rollback but it is throwing an error like,
```
Cannot perform an `add` operation at the desired path
name: OPERATION_PATH_CANNOT_ADD
```
` doc = await doc.rollback(patches[0]._id.toString(), {}, false);`

How do I read read the initial (operation: { op: 'add', ...) record?

**Comment by codepunkt** [comment]
@vinerich any ideas?

**Comment by intermx-reddysai** [comment]
I have three patch records with the same reference Id, to get the first and/or second patch version, it is not working with the rollback.

**Comment by vinerich** [comment]
@codepunkt shouldn't be something with the newest version. (I hope)

@intermx-reddysai can you show us the three patch records and the document you try to rollback?
Thanks!

**Comment by vinerich** [comment]
Hey @intermx-reddysai any news on this? Did you fix your error?
Let us know!

**Comment by intermx-reddysai** [comment]
That was because of ObjectId, it is not working properly on ObjectId.

I had a model field with array of mongoose object Ids. If I update any of the object id, it is not working as expected.

**Comment by vinerich** [comment]
Thanks for your response!
Could you share a few more details with us so we can look into it?

1. Are you updating the array through `push/pop` operations or with `save`?
2. Which plugin config are you using?
3. What exactly is not working as expected? I mean what is happening that is different?

Thanks!
