### ISSUE TITLE
findOneAndUpdate with options { new: true, rawResult: true } throws Error

### ISSUE THREAD

**Issue by maxsimych** [codepunkt/mongoose-patch-history#69]
When the plugin is added to Model and with that model I call:

```javascript
const result = await Model.findOneAndUpdate(query, data, {
    new: true,
    rawResult: true
})
```
Error is throwed: 
**TypeError: document.data is not a function
at mongoose-patch-history/lib/index.js:129:111**

**Comment by vinerich** [comment]
Hey @maxsimych !
Could you provide us your plugin configuration? Thanks!

**Comment by maxsimych** [comment]
node: 14.11.0
mongodb: 3.6.2
mongoose: 5.10.6
mongoose-patch-history: 2.0.0

**Comment by vinerich** [comment]
To get things started could you check the below two points?

1. The issue only appears with the options `{ new: true, rawResult: true }` set? Could you try the different combinations of both parameters and log that here?
2. Just to be sure you apply the plugin like `Model.plugin(patchHistory, config)`?

Thanks !

**Comment by maxsimych** [comment]
1. Yes, only this combination doesn't work. Separately they work without problem.
2. Yes, I do the same)

**Comment by vinerich** [comment]
I think I got you there. @codepunkt will close this issue when PR is merged, shouldn't take too long since it is a small fix.
Hope that will do!

If there's anything else feel free to open another issue 😄

**Comment by codepunkt** [comment]
Merged into master, will be released in next patch release. Until it is, please install directly from GitHub.

Thanks to both of you 👍
